apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    pflaeging.net/instance: peter-test
    pflaeging.net/service: plone-reverse-proxy
  name: peter-test-plone-reverse-proxy
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    pflaeging.net/deployment: nginx-revproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}